version: "3.8"
services:
  web:
    build: .
    image: superbowlquiz:latest
    restart: unless-stopped
    environment:
      WEB_PORT: ${WEB_PORT}
      PGHOST: postgres
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - "./configs:/opt/superbowlquiz/configs"
  admin-console:
    build: .
    image: superbowlquiz:latest
    entrypoint: "npm run admin-console"
    environment:
      PGHOST: postgres
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
  postgres:
    image: postgres:latest
    user: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "${PGPORT}:5432"
  initialize_database:
    image: postgres:latest
    user: postgres
    depends_on: 
      - postgres
    entrypoint: "/mnt/initialize_database.sh"
    environment:
      PGHOST: postgres
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
    volumes:
      - "./database_setup:/mnt"
